version: "2"
services:
  gatsby:
    build: ./
    volumes:
      - ./:/srv
      - /srv/node_modules
      - /srv/.cache
    ports:
      - 7000:8000
    working_dir: /srv
    command: gatsby develop -H 0.0.0.0
